docs: add content and fix problem
mx-space/docs-v2-legacy pull request #27
Opened 2023-08-22 02:24 UTC by wuhang2003

继续搬东西（

2023-08-22 13:53 UTC, wibus-wee commented
不建议自己部署后台，这会带来非常多的不确定性，到时候报错还是怪到文档头上 
除非写到开发者文档中去，这部分还是需要有相关经验的人才能操作，免得出现没必要的麻烦

2023-08-22 13:55 UTC, wibus-wee commented
新的文档还是注重简化操作
进阶操作需要提示提示再提示
警告警告再警告

🙃不想在像过去文档那样什么东西都混在一起了

2023-08-22 13:55 UTC, wibus-wee requested changes
improve again?

2023-08-22 13:59 UTC, wibus-wee requested changes

2023-08-22 13:59 UTC, wibus-wee commented on pages/docs/extra.mdx
> +```
最好不要再出现改源码的事情了
之前的文档关掉的PR写了理由了已经😣

2023-08-22 15:10 UTC, wuhang2003 commented
@wibus-wee 收到建议，大概总结一下内容：
1.删除改源码部分
2.部署后台移到开发者文档
3.部分高风险操作加上提示
你看看还有啥，我过两天忙完再改

2023-08-22 15:12 UTC, wibus-wee commented
ok! 辛苦你啦😭😭

2023-08-25 10:25 UTC, wibus-wee requested changes

2023-08-25 10:25 UTC, wibus-wee commented on pages/development/admin.mdx
> +移动到 `.env.production` 文件，去掉 `VITE_` 前缀的注释符号，然后修改为你的配置。
好像漏了什么（）
另外注释就说：取消对应配置项的注释就好了

2023-08-25 13:30 UTC, wibus-wee commented
是这样的
我在想 自定义redis密码啥的
是不是也应该加在部署章节里辅助填写docker compose的那个组件里面？
这个地方可以原封不动，但是就可以把修改  docker compose 的去掉

2023-08-25 13:57 UTC, wuhang2003 commented
> 是这样的 我在想 自定义redis密码啥的 是不是也应该加在部署章节里辅助填写docker compose的那个组件里面？ 这个地方可以原封不动，但是就可以把修改 docker compose 的去掉

@wibus-wee 那好像得魔改启动脚本了（
启动命令定义在 [docker-run.sh](https://github.com/mx-space/core/blob/master/docker-run.sh)

2023-08-25 14:36 UTC, wibus-wee commented
麻了... 怎么会改成这样
先待定 我问问先

2023-08-25 14:40 UTC, wuhang2003 commented
> 麻了... 怎么会改成这样 先待定 我问问先

彳亍，明天我先补一下升级部分（

2023-08-30 10:55 UTC, wibus-wee requested changes

2023-08-30 10:55 UTC, wibus-wee commented on pages/usage/update.mdx
> +# 更新 Mx-Space
这部分能不能放到个个主题详细页里面？
我觉得这样更便于查阅一点

2023-08-30 10:57 UTC, wuhang2003 commented on pages/usage/update.mdx
> +# 更新 Mx-Space
要分写到主题吗还是给个链接连到这个文档？

> 这部分能不能放到个个主题详细页里面？ 我觉得这样更便于查阅一点

2023-08-30 11:01 UTC, wibus-wee commented on pages/usage/update.mdx
> +# 更新 Mx-Space
我觉得直接放到每个主题部署页面去吧
你也可以再开多一个子页面来讲更新，像shiro写process reporter那样
看看咋样美观（）

2023-08-30 13:11 UTC, wibus-wee approved these changes
gooooooooood

2023-08-30 13:13 UTC, merged